/**
 * Comprehensive ISO 3166-1 alpha-3 to Polish country name mapping.
 * This is the single source of truth for Polish country names in the app.
 */
export const isoToPolishName: Record<string, string> = {
  // Europe
  'ALB': 'Albania',
  'AND': 'Andora',
  'AUT': 'Austria',
  'BLR': 'Białoruś',
  'BEL': 'Belgia',
  'BIH': 'Bośnia i Hercegowina',
  'BGR': 'Bułgaria',
  'HRV': 'Chorwacja',
  'CYP': 'Cypr',
  'CZE': 'Czechy',
  'DNK': 'Dania',
  'EST': 'Estonia',
  'FIN': 'Finlandia',
  'FRA': 'Francja',
  'DEU': 'Niemcy',
  'GRC': 'Grecja',
  'HUN': 'Węgry',
  'ISL': 'Islandia',
  'IRL': 'Irlandia',
  'ITA': 'Włochy',
  'XKX': 'Kosowo',
  'LVA': 'Łotwa',
  'LIE': 'Liechtenstein',
  'LTU': 'Litwa',
  'LUX': 'Luksemburg',
  'MLT': 'Malta',
  'MDA': 'Mołdawia',
  'MCO': 'Monako',
  'MNE': 'Czarnogóra',
  'NLD': 'Holandia',
  'MKD': 'Macedonia Północna',
  'NOR': 'Norwegia',
  'POL': 'Polska',
  'PRT': 'Portugalia',
  'ROU': 'Rumunia',
  'RUS': 'Rosja',
  'SMR': 'San Marino',
  'SRB': 'Serbia',
  'SVK': 'Słowacja',
  'SVN': 'Słowenia',
  'ESP': 'Hiszpania',
  'SWE': 'Szwecja',
  'CHE': 'Szwajcaria',
  'UKR': 'Ukraina',
  'GBR': 'Wielka Brytania',
  'VAT': 'Watykan',
  'XNC': 'Cypr Północny',

  // Asia
  'AFG': 'Afganistan',
  'ARM': 'Armenia',
  'AZE': 'Azerbejdżan',
  'BHR': 'Bahrajn',
  'BGD': 'Bangladesz',
  'BTN': 'Bhutan',
  'BRN': 'Brunei',
  'KHM': 'Kambodża',
  'CHN': 'Chiny',
  'GEO': 'Gruzja',
  'IND': 'Indie',
  'IDN': 'Indonezja',
  'IRN': 'Iran',
  'IRQ': 'Irak',
  'ISR': 'Izrael',
  'JPN': 'Japonia',
  'JOR': 'Jordania',
  'KAZ': 'Kazachstan',
  'KWT': 'Kuwejt',
  'KGZ': 'Kirgistan',
  'LAO': 'Laos',
  'LBN': 'Liban',
  'MYS': 'Malezja',
  'MDV': 'Malediwy',
  'MNG': 'Mongolia',
  'MMR': 'Mjanma (Birma)',
  'NPL': 'Nepal',
  'PRK': 'Korea Północna',
  'OMN': 'Oman',
  'PAK': 'Pakistan',
  'PSE': 'Palestyna',
  'PHL': 'Filipiny',
  'QAT': 'Katar',
  'SAU': 'Arabia Saudyjska',
  'SGP': 'Singapur',
  'KOR': 'Korea Południowa',
  'LKA': 'Sri Lanka',
  'SYR': 'Syria',
  'TWN': 'Tajwan',
  'TJK': 'Tadżykistan',
  'THA': 'Tajlandia',
  'TLS': 'Timor Wschodni',
  'TUR': 'Turcja',
  'TKM': 'Turkmenistan',
  'ARE': 'Zjednoczone Emiraty Arabskie',
  'UZB': 'Uzbekistan',
  'VNM': 'Wietnam',
  'YEM': 'Jemen',

  // Africa
  'DZA': 'Algieria',
  'AGO': 'Angola',
  'BEN': 'Benin',
  'BWA': 'Botswana',
  'BFA': 'Burkina Faso',
  'BDI': 'Burundi',
  'CPV': 'Republika Zielonego Przylądka',
  'CMR': 'Kamerun',
  'CAF': 'Republika Środkowoafrykańska',
  'TCD': 'Czad',
  'COM': 'Komory',
  'COG': 'Kongo',
  'COD': 'Demokratyczna Republika Konga',
  'CIV': 'Wybrzeże Kości Słoniowej',
  'DJI': 'Dżibuti',
  'EGY': 'Egipt',
  'GNQ': 'Gwinea Równikowa',
  'ERI': 'Erytrea',
  'SWZ': 'Eswatini',
  'ETH': 'Etiopia',
  'GAB': 'Gabon',
  'GMB': 'Gambia',
  'GHA': 'Ghana',
  'GIN': 'Gwinea',
  'GNB': 'Gwinea Bissau',
  'KEN': 'Kenia',
  'LSO': 'Lesotho',
  'LBR': 'Liberia',
  'LBY': 'Libia',
  'MDG': 'Madagaskar',
  'MWI': 'Malawi',
  'MLI': 'Mali',
  'MRT': 'Mauretania',
  'MUS': 'Mauritius',
  'MAR': 'Maroko',
  'MOZ': 'Mozambik',
  'NAM': 'Namibia',
  'NER': 'Niger',
  'NGA': 'Nigeria',
  'RWA': 'Rwanda',
  'STP': 'Wyspy Świętego Tomasza i Książęca',
  'SEN': 'Senegal',
  'SYC': 'Seszele',
  'SLE': 'Sierra Leone',
  'SOM': 'Somalia',
  'SOL': 'Somaliland',
  'ZAF': 'Republika Południowej Afryki',
  'SSD': 'Sudan Południowy',
  'SDN': 'Sudan',
  'TZA': 'Tanzania',
  'TGO': 'Togo',
  'TUN': 'Tunezja',
  'UGA': 'Uganda',
  'ZMB': 'Zambia',
  'ZWE': 'Zimbabwe',
  'ESH': 'Sahara Zachodnia',

  // North America
  'ATG': 'Antigua i Barbuda',
  'BHS': 'Bahamy',
  'BRB': 'Barbados',
  'BLZ': 'Belize',
  'CAN': 'Kanada',
  'CRI': 'Kostaryka',
  'CUB': 'Kuba',
  'DMA': 'Dominika',
  'DOM': 'Dominikana',
  'SLV': 'Salwador',
  'GRD': 'Grenada',
  'GTM': 'Gwatemala',
  'HTI': 'Haiti',
  'HND': 'Honduras',
  'JAM': 'Jamajka',
  'MEX': 'Meksyk',
  'NIC': 'Nikaragua',
  'PAN': 'Panama',
  'KNA': 'Saint Kitts i Nevis',
  'LCA': 'Saint Lucia',
  'VCT': 'Saint Vincent i Grenadyny',
  'TTO': 'Trynidad i Tobago',
  'USA': 'Stany Zjednoczone',
  'PRI': 'Portoryko',
  'GRL': 'Grenlandia',

  // South America
  'ARG': 'Argentyna',
  'BOL': 'Boliwia',
  'BRA': 'Brazylia',
  'CHL': 'Chile',
  'COL': 'Kolumbia',
  'ECU': 'Ekwador',
  'GUY': 'Gujana',
  'PRY': 'Paragwaj',
  'PER': 'Peru',
  'SUR': 'Surinam',
  'URY': 'Urugwaj',
  'VEN': 'Wenezuela',
  'GUF': 'Gujana Francuska',
  'FLK': 'Falklandy',

  // Oceania
  'AUS': 'Australia',
  'FJI': 'Fidżi',
  'KIR': 'Kiribati',
  'MHL': 'Wyspy Marshalla',
  'FSM': 'Mikronezja',
  'NRU': 'Nauru',
  'NZL': 'Nowa Zelandia',
  'PLW': 'Palau',
  'PNG': 'Papua-Nowa Gwinea',
  'WSM': 'Samoa',
  'SLB': 'Wyspy Salomona',
  'TON': 'Tonga',
  'TUV': 'Tuvalu',
  'VUT': 'Vanuatu',
  'NCL': 'Nowa Kaledonia',

  // Territories and special regions
  'ATA': 'Antarktyda',
  'HKG': 'Hongkong',
  'MAC': 'Makau',
  'ABW': 'Aruba',
  'AIA': 'Anguilla',
  'BMU': 'Bermudy',
  'VGB': 'Brytyjskie Wyspy Dziewicze',
  'CYM': 'Kajmany',
  'CUW': 'Curaçao',
  'GIB': 'Gibraltar',
  'GLP': 'Gwadelupa',
  'MTQ': 'Martynika',
  'SXM': 'Sint Maarten',
  'TCA': 'Turks i Caicos',
  'VIR': 'Wyspy Dziewicze Stanów Zjednoczonych',
  'REU': 'Reunion',
  'MYT': 'Majotta',
  'SPM': 'Saint-Pierre i Miquelon',
  'WLF': 'Wallis i Futuna',
  'PYF': 'Polinezja Francuska',
  'ASM': 'Samoa Amerykańskie',
  'GUM': 'Guam',
  'MNP': 'Mariany Północne',
  'PCN': 'Pitcairn',
  'SHN': 'Wyspa Świętej Heleny',
  'SGS': 'Georgia Południowa i Sandwich Południowy',
  'IOT': 'Brytyjskie Terytorium Oceanu Indyjskiego',
  'CCK': 'Wyspy Kokosowe',
  'CXR': 'Wyspa Bożego Narodzenia',
  'HMD': 'Wyspy Heard i McDonalda',
  'NFK': 'Norfolk',
  'TKL': 'Tokelau',
  'COK': 'Wyspy Cooka',
  'NIU': 'Niue',
};

/**
 * Get Polish name for a country by its ISO alpha-3 code
 */
export function getPolishName(isoCode: string): string {
  const code = isoCode.toUpperCase();
  return isoToPolishName[code] || code;
}

/**
 * Get all Polish country names sorted alphabetically
 */
export function getAllPolishNames(): Array<{ code: string; name: string }> {
  return Object.entries(isoToPolishName)
    .map(([code, name]) => ({ code, name }))
    .sort((a, b) => a.name.localeCompare(b.name, 'pl'));
}

/**
 * Search for countries by Polish name
 */
export function searchPolishCountries(query: string): Array<{ code: string; name: string }> {
  const normalizedQuery = query.toLowerCase();
  return Object.entries(isoToPolishName)
    .filter(([_, name]) => name.toLowerCase().includes(normalizedQuery))
    .map(([code, name]) => ({ code, name }))
    .sort((a, b) => a.name.localeCompare(b.name, 'pl'));
}
