-- Create enum for country status
CREATE TYPE public.country_status AS ENUM ('available', 'coming_soon', 'soon', 'none');

-- Create table for country statuses
CREATE TABLE public.country_statuses (
  id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  country_code TEXT NOT NULL UNIQUE,
  country_name TEXT NOT NULL,
  status public.country_status NOT NULL DEFAULT 'none',
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);

-- Enable RLS
ALTER TABLE public.country_statuses ENABLE ROW LEVEL SECURITY;

-- Anyone can view country statuses (for map display)
CREATE POLICY "Anyone can view country statuses"
ON public.country_statuses
FOR SELECT
USING (true);

-- Admins can insert country statuses
CREATE POLICY "Admins can insert country statuses"
ON public.country_statuses
FOR INSERT
WITH CHECK (is_admin(auth.uid()));

-- Admins can update country statuses
CREATE POLICY "Admins can update country statuses"
ON public.country_statuses
FOR UPDATE
USING (is_admin(auth.uid()));

-- Admins can delete country statuses
CREATE POLICY "Admins can delete country statuses"
ON public.country_statuses
FOR DELETE
USING (is_admin(auth.uid()));

-- Create trigger for updated_at
CREATE TRIGGER update_country_statuses_updated_at
BEFORE UPDATE ON public.country_statuses
FOR EACH ROW
EXECUTE FUNCTION public.update_updated_at_column();

-- Insert all world countries with default 'none' status
INSERT INTO public.country_statuses (country_code, country_name, status) VALUES
  ('AFG', 'Afganistan', 'none'),
  ('ALB', 'Albania', 'none'),
  ('DZA', 'Algieria', 'none'),
  ('AND', 'Andora', 'none'),
  ('AGO', 'Angola', 'none'),
  ('ATG', 'Antigua i Barbuda', 'none'),
  ('ARG', 'Argentyna', 'available'),
  ('ARM', 'Armenia', 'none'),
  ('AUS', 'Australia', 'coming_soon'),
  ('AUT', 'Austria', 'none'),
  ('AZE', 'Azerbejdżan', 'none'),
  ('BHS', 'Bahamy', 'none'),
  ('BHR', 'Bahrajn', 'none'),
  ('BGD', 'Bangladesz', 'none'),
  ('BRB', 'Barbados', 'none'),
  ('BEL', 'Belgia', 'none'),
  ('BLZ', 'Belize', 'none'),
  ('BEN', 'Benin', 'none'),
  ('BTN', 'Bhutan', 'none'),
  ('BOL', 'Boliwia', 'none'),
  ('BIH', 'Bośnia i Hercegowina', 'none'),
  ('BWA', 'Botswana', 'none'),
  ('BRA', 'Brazylia', 'coming_soon'),
  ('BRN', 'Brunei', 'none'),
  ('BGR', 'Bułgaria', 'none'),
  ('BFA', 'Burkina Faso', 'none'),
  ('BDI', 'Burundi', 'none'),
  ('CHL', 'Chile', 'none'),
  ('CHN', 'Chiny', 'coming_soon'),
  ('HRV', 'Chorwacja', 'none'),
  ('CYP', 'Cypr', 'none'),
  ('TCD', 'Czad', 'none'),
  ('MNE', 'Czarnogóra', 'none'),
  ('CZE', 'Czechy', 'none'),
  ('DNK', 'Dania', 'none'),
  ('COD', 'Demokratyczna Republika Konga', 'none'),
  ('DMA', 'Dominika', 'none'),
  ('DOM', 'Dominikana', 'none'),
  ('DJI', 'Dżibuti', 'none'),
  ('EGY', 'Egipt', 'coming_soon'),
  ('ECU', 'Ekwador', 'none'),
  ('ERI', 'Erytrea', 'none'),
  ('EST', 'Estonia', 'none'),
  ('SWZ', 'Eswatini', 'none'),
  ('ETH', 'Etiopia', 'none'),
  ('FJI', 'Fidżi', 'none'),
  ('PHL', 'Filipiny', 'none'),
  ('FIN', 'Finlandia', 'none'),
  ('FRA', 'Francja', 'available'),
  ('GAB', 'Gabon', 'none'),
  ('GMB', 'Gambia', 'none'),
  ('GHA', 'Ghana', 'none'),
  ('GRC', 'Grecja', 'coming_soon'),
  ('GRD', 'Grenada', 'none'),
  ('GEO', 'Gruzja', 'none'),
  ('GUY', 'Gujana', 'none'),
  ('GTM', 'Gwatemala', 'none'),
  ('GIN', 'Gwinea', 'none'),
  ('GNB', 'Gwinea Bissau', 'none'),
  ('GNQ', 'Gwinea Równikowa', 'none'),
  ('HTI', 'Haiti', 'none'),
  ('ESP', 'Hiszpania', 'available'),
  ('NLD', 'Holandia', 'coming_soon'),
  ('HND', 'Honduras', 'none'),
  ('IND', 'Indie', 'coming_soon'),
  ('IDN', 'Indonezja', 'none'),
  ('IRQ', 'Irak', 'none'),
  ('IRN', 'Iran', 'none'),
  ('IRL', 'Irlandia', 'none'),
  ('ISL', 'Islandia', 'coming_soon'),
  ('ISR', 'Izrael', 'none'),
  ('JAM', 'Jamajka', 'none'),
  ('JPN', 'Japonia', 'coming_soon'),
  ('YEM', 'Jemen', 'none'),
  ('JOR', 'Jordania', 'none'),
  ('KHM', 'Kambodża', 'none'),
  ('CMR', 'Kamerun', 'none'),
  ('CAN', 'Kanada', 'coming_soon'),
  ('QAT', 'Katar', 'none'),
  ('KAZ', 'Kazachstan', 'none'),
  ('KEN', 'Kenia', 'coming_soon'),
  ('KGZ', 'Kirgistan', 'none'),
  ('KIR', 'Kiribati', 'none'),
  ('COL', 'Kolumbia', 'none'),
  ('COM', 'Komory', 'none'),
  ('COG', 'Kongo', 'none'),
  ('KOR', 'Korea Południowa', 'coming_soon'),
  ('PRK', 'Korea Północna', 'none'),
  ('CRI', 'Kostaryka', 'none'),
  ('CUB', 'Kuba', 'none'),
  ('KWT', 'Kuwejt', 'none'),
  ('LAO', 'Laos', 'none'),
  ('LSO', 'Lesotho', 'none'),
  ('LBN', 'Liban', 'none'),
  ('LBR', 'Liberia', 'none'),
  ('LBY', 'Libia', 'none'),
  ('LIE', 'Liechtenstein', 'none'),
  ('LTU', 'Litwa', 'none'),
  ('LUX', 'Luksemburg', 'none'),
  ('LVA', 'Łotwa', 'none'),
  ('MKD', 'Macedonia Północna', 'none'),
  ('MDG', 'Madagaskar', 'none'),
  ('MWI', 'Malawi', 'none'),
  ('MDV', 'Malediwy', 'none'),
  ('MYS', 'Malezja', 'none'),
  ('MLI', 'Mali', 'none'),
  ('MLT', 'Malta', 'none'),
  ('MAR', 'Maroko', 'coming_soon'),
  ('MRT', 'Mauretania', 'none'),
  ('MUS', 'Mauritius', 'none'),
  ('MEX', 'Meksyk', 'coming_soon'),
  ('FSM', 'Mikronezja', 'none'),
  ('MMR', 'Mjanma', 'none'),
  ('MDA', 'Mołdawia', 'none'),
  ('MCO', 'Monako', 'none'),
  ('MNG', 'Mongolia', 'none'),
  ('MOZ', 'Mozambik', 'none'),
  ('NAM', 'Namibia', 'none'),
  ('NRU', 'Nauru', 'none'),
  ('NPL', 'Nepal', 'none'),
  ('DEU', 'Niemcy', 'available'),
  ('NER', 'Niger', 'none'),
  ('NGA', 'Nigeria', 'none'),
  ('NIC', 'Nikaragua', 'none'),
  ('NOR', 'Norwegia', 'coming_soon'),
  ('NZL', 'Nowa Zelandia', 'coming_soon'),
  ('OMN', 'Oman', 'none'),
  ('PAK', 'Pakistan', 'none'),
  ('PLW', 'Palau', 'none'),
  ('PAN', 'Panama', 'none'),
  ('PNG', 'Papua-Nowa Gwinea', 'none'),
  ('PRY', 'Paragwaj', 'none'),
  ('PER', 'Peru', 'coming_soon'),
  ('POL', 'Polska', 'available'),
  ('PRT', 'Portugalia', 'none'),
  ('ZAF', 'Republika Południowej Afryki', 'coming_soon'),
  ('CAF', 'Republika Środkowoafrykańska', 'none'),
  ('RUS', 'Rosja', 'none'),
  ('ROU', 'Rumunia', 'none'),
  ('RWA', 'Rwanda', 'none'),
  ('KNA', 'Saint Kitts i Nevis', 'none'),
  ('LCA', 'Saint Lucia', 'none'),
  ('VCT', 'Saint Vincent i Grenadyny', 'none'),
  ('SLV', 'Salwador', 'none'),
  ('WSM', 'Samoa', 'none'),
  ('SMR', 'San Marino', 'none'),
  ('SEN', 'Senegal', 'none'),
  ('SRB', 'Serbia', 'none'),
  ('SYC', 'Seszele', 'none'),
  ('SLE', 'Sierra Leone', 'none'),
  ('SGP', 'Singapur', 'none'),
  ('SVK', 'Słowacja', 'none'),
  ('SVN', 'Słowenia', 'none'),
  ('SOM', 'Somalia', 'none'),
  ('LKA', 'Sri Lanka', 'none'),
  ('USA', 'Stany Zjednoczone', 'coming_soon'),
  ('SDN', 'Sudan', 'none'),
  ('SSD', 'Sudan Południowy', 'none'),
  ('SUR', 'Surinam', 'none'),
  ('SYR', 'Syria', 'none'),
  ('CHE', 'Szwajcaria', 'none'),
  ('SWE', 'Szwecja', 'coming_soon'),
  ('TJK', 'Tadżykistan', 'none'),
  ('THA', 'Tajlandia', 'coming_soon'),
  ('TWN', 'Tajwan', 'none'),
  ('TZA', 'Tanzania', 'none'),
  ('TLS', 'Timor Wschodni', 'none'),
  ('TGO', 'Togo', 'none'),
  ('TON', 'Tonga', 'none'),
  ('TTO', 'Trynidad i Tobago', 'none'),
  ('TUN', 'Tunezja', 'none'),
  ('TUR', 'Turcja', 'coming_soon'),
  ('TKM', 'Turkmenistan', 'none'),
  ('TUV', 'Tuvalu', 'none'),
  ('UGA', 'Uganda', 'none'),
  ('UKR', 'Ukraina', 'none'),
  ('URY', 'Urugwaj', 'none'),
  ('UZB', 'Uzbekistan', 'none'),
  ('VUT', 'Vanuatu', 'none'),
  ('VAT', 'Watykan', 'none'),
  ('VEN', 'Wenezuela', 'none'),
  ('HUN', 'Węgry', 'none'),
  ('GBR', 'Wielka Brytania', 'available'),
  ('VNM', 'Wietnam', 'coming_soon'),
  ('ITA', 'Włochy', 'available'),
  ('CIV', 'Wybrzeże Kości Słoniowej', 'none'),
  ('BVT', 'Wyspa Bouveta', 'none'),
  ('STP', 'Wyspy Świętego Tomasza i Książęca', 'none'),
  ('MHL', 'Wyspy Marshalla', 'none'),
  ('SLB', 'Wyspy Salomona', 'none'),
  ('ZMB', 'Zambia', 'none'),
  ('ZWE', 'Zimbabwe', 'none'),
  ('ARE', 'Zjednoczone Emiraty Arabskie', 'none');